import { uid } from "@/lib/id";
import type { Meal, MealDraft } from "@/lib/types";

/** Starter list so a fresh install has something to spin on day one. */
const DRAFTS: MealDraft[] = [
  {
    name: "פסטה ברוטב עגבניות",
    emoji: "🍝",
    categories: ["dinner", "lunch"],
    kind: "home",
    tags: ["צמחוני", "מהיר"],
    prepMinutes: 25,
    cost: 1,
    weight: 4,
    enabled: true,
    favorite: true,
  },
  {
    name: "שקשוקה",
    emoji: "🍳",
    categories: ["breakfast", "dinner"],
    kind: "home",
    tags: ["צמחוני", "חריף"],
    prepMinutes: 20,
    cost: 1,
    weight: 4,
    enabled: true,
    favorite: false,
  },
  {
    name: "חומוס עם פול",
    emoji: "🥣",
    categories: ["breakfast", "lunch"],
    kind: "takeout",
    tags: ["צמחוני"],
    prepMinutes: 10,
    cost: 1,
    weight: 3,
    enabled: true,
    favorite: false,
  },
  {
    name: "פיצה",
    emoji: "🍕",
    categories: ["dinner"],
    kind: "takeout",
    tags: ["comfort"],
    prepMinutes: 30,
    cost: 2,
    weight: 3,
    enabled: true,
    favorite: true,
  },
  {
    name: "סושי",
    emoji: "🍣",
    categories: ["dinner", "lunch"],
    kind: "restaurant",
    tags: ["דגים"],
    prepMinutes: 45,
    cost: 3,
    weight: 2,
    enabled: true,
    favorite: false,
  },
  {
    name: "חביתה וסלט",
    emoji: "🥗",
    categories: ["breakfast"],
    kind: "home",
    tags: ["מהיר", "בריא"],
    prepMinutes: 12,
    cost: 1,
    weight: 3,
    enabled: true,
    favorite: false,
  },
  {
    name: "המבורגר",
    emoji: "🍔",
    categories: ["dinner", "lunch"],
    kind: "restaurant",
    tags: ["בשרי"],
    prepMinutes: 35,
    cost: 3,
    weight: 2,
    enabled: true,
    favorite: false,
  },
  {
    name: "מרק עדשים",
    emoji: "🍲",
    categories: ["dinner"],
    kind: "home",
    tags: ["צמחוני", "חורף"],
    prepMinutes: 40,
    cost: 1,
    weight: 2,
    enabled: true,
    favorite: false,
  },
  {
    name: "סלט יווני",
    emoji: "🥙",
    categories: ["lunch"],
    kind: "home",
    tags: ["בריא", "מהיר"],
    prepMinutes: 15,
    cost: 2,
    weight: 3,
    enabled: true,
    favorite: false,
  },
  {
    name: "פלאפל בפיתה",
    emoji: "🧆",
    categories: ["lunch"],
    kind: "takeout",
    tags: ["צמחוני", "מהיר"],
    prepMinutes: 10,
    cost: 1,
    weight: 3,
    enabled: true,
    favorite: false,
  },
  {
    name: "אורז עם ירקות מוקפצים",
    emoji: "🍚",
    categories: ["dinner", "lunch"],
    kind: "home",
    tags: ["צמחוני"],
    prepMinutes: 25,
    cost: 1,
    weight: 3,
    enabled: true,
    favorite: false,
  },
  {
    name: "טוסט גבינות",
    emoji: "🥪",
    categories: ["breakfast", "snack"],
    kind: "home",
    tags: ["מהיר"],
    prepMinutes: 8,
    cost: 1,
    weight: 3,
    enabled: true,
    favorite: false,
  },
  {
    name: "עוף בתנור",
    emoji: "🍗",
    categories: ["dinner"],
    kind: "home",
    tags: ["בשרי"],
    prepMinutes: 60,
    cost: 2,
    weight: 3,
    enabled: true,
    favorite: true,
  },
  {
    name: "פנקייקים",
    emoji: "🥞",
    categories: ["breakfast", "dessert"],
    kind: "home",
    tags: ["מתוק"],
    prepMinutes: 20,
    cost: 1,
    weight: 2,
    enabled: true,
    favorite: false,
  },
  {
    name: "טאקוס",
    emoji: "🌮",
    categories: ["dinner"],
    kind: "restaurant",
    tags: ["חריף"],
    prepMinutes: 30,
    cost: 2,
    weight: 2,
    enabled: true,
    favorite: false,
  },
  {
    name: "גלידה",
    emoji: "🍨",
    categories: ["dessert", "snack"],
    kind: "takeout",
    tags: ["מתוק"],
    prepMinutes: 5,
    cost: 1,
    weight: 2,
    enabled: true,
    favorite: false,
  },
];

export function seedMeals(): Meal[] {
  const now = Date.now();
  return DRAFTS.map((draft, i) => ({
    ...draft,
    id: uid("meal"),
    createdAt: now + i,
    updatedAt: now + i,
  }));
}
